### ISSUE TITLE
netx90 openocd scripts

### ISSUE THREAD

**Issue by tejainece** [mtrensch/netx_openocd_scripts#1]

**Comment by mtrensch** [comment]
I assumed, as there was no further description, you meant netX90 supporting scripts.
I've added them now, so this issue should be closed

**Comment by tejainece** [comment]
Thanks! I will test the new next90 scripts.

I noticed that config script for netx90 is missing: https://github.com/mtrensch/netx_openocd_scripts/tree/master/config. It seems other config scripts are just scouring other scripts from target and interface.

Unrelated question, do you work for Hilscher?

**Comment by mtrensch** [comment]
> I noticed that config script for netx90 is missing: https://github.com/mtrensch/netx_openocd_scripts/tree/master/config. It seems other config scripts are just scouring other scripts from target and interface.

Those scripts were meant for easier starting of openOCD (and for lazy guys like me). Basically you can only use the files in boards + interfaces, which is the default in openOCD.
`openocd -f interface/hilscher_nxhx90_jtag.cfg -f board/hilscher_nxhx90_jtag.cfg` is the same as `openocd -f config/nxhx90_jtag`.

Added it now as b06a0552ea82d8c9a500936f7dc74affd8a69e61

> Unrelated question, do you work for Hilscher?

Yes, but the openOCD scripts hosted here were a private project at start and still are. I

**Comment by tejainece** [comment]
Nice! Thanks for quick response.
